version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - depguard
    - dupword
    - err113
    - errname
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - paralleltest
    - tagalign
    - tagliatelle
    - testableexamples
    - varnamelen
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    misspell:
      locale: US
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - err113
          - funlen
          - goconst
          - mnd
          - noctx
          - nosnakecase
          - structcheck
          - unparam
          - unused
        path: _test.go
      - linters:
          - errcheck
          - gosec
        path: example_
      - linters:
          - revive
          - staticcheck
        text: Html
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
